spring:
    datasource:
        testWhileIdle: true
        url: jdbc:mysql:///myhome?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: false