package com.heiliuer.youku.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "record")
public class Record {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotNull
    private Integer videoId;

    private Long createTime;

    private Long latestCheckTime;

    @NotNull
    private Integer showId;

    @NotNull
    private String name;

    @NotNull
    private Integer episodeLast;


    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getLatestCheckTime() {
        return latestCheckTime;
    }

    public void setLatestCheckTime(Long latestCheckTime) {
        this.latestCheckTime = latestCheckTime;
    }

// Public methods

    public Record() {
        createTime = System.currentTimeMillis();
    }


    public Integer getEpisodeLast() {
        return episodeLast;
    }

    public void setEpisodeLast(Integer episodeLast) {
        this.episodeLast = episodeLast;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getVideoId() {
        return videoId;
    }

    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    public Integer getShowId() {
        return showId;
    }

    public void setShowId(Integer showId) {
        this.showId = showId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}